spring:
  jpa:
    properties:
      hibernate:
        hibernate.format_sql: true
        jdbc:
          lob.non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    format_sql: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
    #tomcat:
    #  initial-size: 1
  security:
    secret:
      key: secreto
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
movie:
  rental:
    days:
      for:
       renting: 3
    penalty:
      percentage: 0.05